### ISSUE TITLE
Free Tuning Bug

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_lscustom#18] opened 2018-02-16 13:18 UTC
If someone chooses the given part of tuning and then opens a different menu, for example from the billing, this part is assembled for free.

**Comment by JaroSound** [comment] 2018-04-05 22:51
Any fix?

**Comment by nykroza** [comment] 2018-07-08 01:17
the problem is still around, if we change one car and a new one come inside the LSCustom and just hit backspace, he will have all the modification of the last car.

**Comment by ElPumpo** [comment] 2018-09-02 10:47
Fixed in 7ae6bbb87b34d956963e28018da685268ec99aed

**Closed by ElPumpo** 2018-09-02 10:47 UTC
Labels: bug

**Comment by Xseba360** [comment] 2019-05-11 14:33
Apparently you can still get free tuning when you select a modification - and leave the server (ie. quit in console, alt f4)
