### ISSUE TITLE
Sticker / Livery Default?

### ISSUE THREAD

**Issue by JaroSound** [ESX-Org/esx_lscustom#56] opened 2019-01-01 23:15 UTC
While in the Stickers/Livery section, the option says "default", however I can click up and down arrow and then the stickers change. Is there a way to fix this, so instead of "Default" there will be numbers?

**Comment by ElPumpo** [comment] 2019-01-18 09:42
Have you updated to https://github.com/ESX-Org/es_extended/commit/5e35663c95135c5980abe9f2daa8de2d95eeac36

**Comment by ElPumpo** [comment] 2019-01-18 09:43
Duplicate of #23

**Closed by ElPumpo** 2019-01-18 09:43 UTC
Labels: bug, question
