### ISSUE TITLE
I can't custom my add-on car

### ISSUE THREAD

**Issue by supergeek23** [ESX-Org/esx_lscustom#37] opened 2018-08-14 20:51 UTC
Hello. For the first time thank you very much for you nice job, all of your work are awesome but I have a little problem (sorry for my bad english i'm french ^^), i install a lot of add-on car like most server in Fivem but I can't custom that in the LS Custom. Some of add-on car have a lot of car modification like custom spoiler... But i don't have this custom in LsCustom and in Mellotraine, but the custom is in the file. And it's not all, all of my add-ons car can't be modified, i have only the upgrade in lvl 2 or 3 max not 4 and when i put any custom i buy that but i don't have that in the car. Sorry for my bad english again and thank you very much if you have the solution. ^^

**Comment by ElPumpo** [comment] 2018-09-28 22:03
Duplicate of #23

**Closed by ElPumpo** 2018-09-28 22:03 UTC
Labels: duplicate

**Comment by LysyProboszcz** [comment] 2020-09-25 12:57
You solved this problem ?
