### ISSUE TITLE
Free part on backspace

### ISSUE THREAD

**Issue by nykroza** [ESX-Org/esx_lscustom#29] opened 2018-07-11 17:34 UTC
As soon as we modifie the first car there is no problem at all.. but when we enter in the second car, then in the LSCustom menu we just have to hit backspace and it will get all the modification of the previous car and for free .. I don't have any error, the script is freshly downloaded and installed, no modification made to the script.. here is a video of what it is doing : https://youtu.be/hD0PbFhXI7M

**Comment by ElPumpo** [comment] 2018-08-05 07:49
duplicate of #18

**Closed by ElPumpo** 2018-08-05 07:49 UTC
